apiVersion: v1 
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd-minimal
  labels:
    app.kubernetes.io/part-of: argocd
data:
  url: "http://localhost:8081"
  application.instanceLabelKey: "argocd.argoproj.io/instance"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd-minimal
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, accounts, *, *, allow
    g, admin, role:admin

